#!/usr/bin/env bash
#
# render image $1 in prez
#
# dependencies:
#  w3m
#  ImageMagick

IFS='[;' read -p $'\e[6n' -d R -rs _ y x _
# https://github.com/dylanaraps/pure-bash-bible#get-the-current-cursor-position

w3m_img="/usr/lib/w3m/w3mimgdisplay"
ltr_w=9
ltr_h=18

cols="$(tput cols)"
rows="$(tput lines)"


x_sz="$(convert $1 -format '%[w]' info:)"
y_sz="$(convert $1 -format '%[h]' info:)"

while [ $((x_sz / ltr_w)) -gt "$cols" ]
do
	x_sz=$((x_sz/2))
	y_sz=$((y_sz/2))
done

while [ $((y_sz / ltr_h)) -gt "$rows" ]
do
	x_sz=$((x_sz/2))
	y_sz=$((y_sz/2))
done

echo 

for i in $(seq $(($y_sz / $ltr_h)))
do
	echo
done

echo -e "0;1;0;0;$x_sz;$y_sz;;;;;$1\n4;\n3;" | "$w3m_img" &
